### ISSUE TITLE
Open Menu from second page

### ISSUE THREAD

**Issue by syn-satishku** [kiran5232/SideMenuSwiftDemo#2]
Hi, I know this is not the good place to write, but i have not found any other way to catch you please 
excuse.

I am using you code in my app and i want to attach menu from second page, my first page is just introduction page with some buttons to decide where to go for example Login, Registration or Skip. but i am not able to find any solution that works for me, if you mind could you please help me to resolve or its better if you add one more page in you app that open menu from second page.

**Comment by KiranPatelSpaceo** [comment]
Hi, You have to call following method with your controller identifier name after Successful login or registration process.
kConstantObj.SetIntialMainViewController("firstVC")  //replace with your controller identifier name in place of  firstVC

And also app delegate you have to set you login vc as root view controller.

Thanks
