### ISSUE TITLE
swift 3.0 support

### ISSUE THREAD

**Issue by hardik99** [kiran5232/SideMenuSwiftDemo#3]

**Comment by dipsvaishnav** [comment]
I got error in Swift 3.0 Method
Method SetMenuViewController with Objective-C selector setMenuViewController: conflicts with setter for menuViewController with the same objective -C selector

**Comment by davut5** [comment]
did u make it with swift 3.0?

**Comment by dipsvaishnav** [comment]
Tnx for replay i resolve issue.

Deepak Kumar Vaishnav

**Comment by dipsvaishnav** [comment]
Yes i use in Swift 3.0

Deepak Kumar Vaishnav

**Comment by dipsvaishnav** [comment]
Please add pinch in Menu

Deepak Kumar Vaishnav

**Comment by KiranPatelSpaceo** [comment]
Hi,

Fixed it 
Latest code supported swift version 3.2

Thanks

**Comment by dipsvaishnav** [comment]
Tnx but plase add Pinch

Deepak Kumar Vaishnav
